# Generated by Django 5.1 on 2024-09-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_list_item_list"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ("id",)},
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("list", "text")},
        ),
    ]
