# Generated by Django 5.1 on 2024-09-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_alter_item_options_alter_item_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(default="", unique=True),
        ),
    ]
