# Generated by Django 5.1 on 2024-09-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0005_alter_item_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(default=""),
        ),
    ]
